spring.application.name=livent
spring.sql.init.mode=never

spring.r2dbc.url=${SPRING_R2DBC_URL:r2dbc:h2:mem:///livent;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.r2dbc.username=${SPRING_R2DBC_USERNAME:sa}
spring.r2dbc.password=${SPRING_R2DBC_PASSWORD:}
spring.flyway.url=${SPRING_FLYWAY_URL:jdbc:h2:mem:livent;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.flyway.user=${SPRING_FLYWAY_USER:sa}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD:}
